### ISSUE TITLE
A newly started cluster from this example is not becoming HA

### ISSUE THREAD

**Issue by jimklimov** [garutilorenzo/mysql-ha-docker#3]
It seems that as the two mysql instances are initializing for the first time, they race to become a master on one side, and waiting to find a master on the other.

In the log I see a series of connection errors, and ultimately it fails with a duplicate primary key in the heartbeat table. Most of the time. A few times "orchestrator" showed the two servers decided to become two independent masters (I guess the second one began a failover due to the issues, and the first one did not support the coup-d-etat).

I wiped and restarted this setup maybe a dozen times over a few days (`docker-compose down -v ; sleep 15 ; docker-compose up`), and rebooted the Debian 11 VM it was tested in, and never saw the replication working.

**Comment by jimklimov** [comment]
UPDATE: Re-trying with `docker-compose down -v ; sleep 15 ; docker-compose up --force-recreate` to start from scratch even more intensely, and after rebooting the host of that VM to hopefully rule out lags from the long-running host OS. Even if that latter part about lags helps, it would only substantiate that there is some raciness and/or wallclock time(out) dependency that makes this solution fragile. But if it works, I'd at least have a playground for experiments :)

**Comment by garutilorenzo** [comment]
Possible solution for this problem are commit f995fa145d7dd2a11da6a0228acbb952b487d81e and 311e73e7dee1e0b7cc0d352201186cff23e7edc1

But in my local lab all things work correctly:


```
    Last_SQL_Error_Timestamp: 
               Master_SSL_Crl: 
           Master_SSL_Crlpath: 
           Retrieved_Gtid_Set: 9e0a1991-26b1-11ec-964c-0242ac380002:1-826
            Executed_Gtid_Set: 9e0a1991-26b1-11ec-964c-0242ac380002:1-826
                Auto_Position: 1
         Replicate_Rewrite_DB: 
                 Channel_Name: 
           Master_TLS_Version: 
1 row in set (0.00 sec)
```

```
mysql> select * from percona.heartbeat;
+----------------------------+-----------+------------------+----------+-----------------------+---------------------+
| ts                         | server_id | file             | position | relay_master_log_file | exec_master_log_pos |
+----------------------------+-----------+------------------+----------+-----------------------+---------------------+
| 2021-10-06T16:43:53.006120 |         2 | mysql-bin.000003 |   354572 | NULL                  |                NULL |
+----------------------------+-----------+------------------+----------+-----------------------+---------------------+
1 row in set (0.00 sec)

mysql> select * from percona.heartbeat;
+----------------------------+-----------+------------------+----------+-----------------------+---------------------+
| ts                         | server_id | file             | position | relay_master_log_file | exec_master_log_pos |
+----------------------------+-----------+------------------+----------+-----------------------+---------------------+
| 2021-10-06T16:43:55.004310 |         2 | mysql-bin.000003 |   355346 | NULL                  |                NULL |
+----------------------------+-----------+------------------+----------+-----------------------+---------------------+
1 row in set (0.00 sec)
```

I close the issue for the moment.
